// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXx7VFnCix-SyUuzwxxc_pS2UdH73VMmc',
    appId: '1:760709742016:web:da25ccfeab16787aafdc25',
    messagingSenderId: '760709742016',
    projectId: 'linkhub-pavani',
    authDomain: 'linkhub-pavani.firebaseapp.com',
    storageBucket: 'linkhub-pavani.firebasestorage.app',
    measurementId: 'G-CGYV3VWCMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhhb-57fP9NZ01cvgzBpfgWh3o9Zp6lmg',
    appId: '1:760709742016:android:50aa2a4d0b6ff0b1afdc25',
    messagingSenderId: '760709742016',
    projectId: 'linkhub-pavani',
    storageBucket: 'linkhub-pavani.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcX_7jxsbreYaU8kWxCAPcxXJleXJiC9Q',
    appId: '1:760709742016:ios:0b4be68a2e213418afdc25',
    messagingSenderId: '760709742016',
    projectId: 'linkhub-pavani',
    storageBucket: 'linkhub-pavani.firebasestorage.app',
    iosBundleId: 'com.example.linkhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcX_7jxsbreYaU8kWxCAPcxXJleXJiC9Q',
    appId: '1:760709742016:ios:0b4be68a2e213418afdc25',
    messagingSenderId: '760709742016',
    projectId: 'linkhub-pavani',
    storageBucket: 'linkhub-pavani.firebasestorage.app',
    iosBundleId: 'com.example.linkhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXx7VFnCix-SyUuzwxxc_pS2UdH73VMmc',
    appId: '1:760709742016:web:ed1dc32fb81f9175afdc25',
    messagingSenderId: '760709742016',
    projectId: 'linkhub-pavani',
    authDomain: 'linkhub-pavani.firebaseapp.com',
    storageBucket: 'linkhub-pavani.firebasestorage.app',
    measurementId: 'G-RYJL22HGB3',
  );

}